version: "3.9"

services:
  payment_app:
    image: cloud-provider-payment8001:1.0-SNAPSHOT
    ports:
      - "8001:8001"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/db2019?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      DB_HOST: db
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: db2019
    ports:
      - "3306:3306"
    volumes:
      - cloud-provider-payment8001:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
  consumer_app:
    image: cloud-consumer80:1.0-SNAPSHOT
    ports:
      - "80:80"
    environment:
      PAYMENT_URL: http://payment_app:8001
    depends_on:
      - payment_app
volumes:
  cloud-provider-payment8001:
