spring:
  application:
    name: cloud-order-service

server:
  port: 80

payment:
  url: ${PAYMENT_URL:http://localhost:8001}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_INSTANCE_HOSTNAME:localhost}:${EUREKA_INSTANCE_PORT:7001}/eureka/
  instance:
    prefer-ip-address: true