spring:
  application:
    name: cloud-payment-service
  # spring boot官方文档: 4.11. Working with SQL Databases
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  sql:
    init:
      mode: always
      encoding: UTF-8

server:
  port: 8001

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lvhao.entity

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_INSTANCE_HOSTNAME:localhost}:${EUREKA_INSTANCE_PORT:7001}/eureka/
  instance:
    prefer-ip-address: true