spring:
  application:
    name: cloud-payment-service
  # spring boot官方文档: 4.11. Working with SQL Databases
  datasource:
    url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

server:
  port: 8001

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lvhao.springcloud.entities

