server:
  port: 7001
eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
  client:
    # 不注册当前服务(eureka server)到eureka
    register-with-eureka: false
    # 当前服务(eureka server)无需从eureka server获取registry
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #  Netflix's original version of the Eureka Server avoids answering clients for a configurable period of time if
      # it starts with an empty registry. The waitTimeInMsWhenSyncEmpty property controls this behavior, and it was
      # designed so that clients would not get partial/empty registry information until the server has had enough time
      # to build the registry. In the previous example, it is set to zero, to start answering clients as soon as possible.
      # If not set, the default value for the server.waitTimeInMsWhenSyncEmpty is 5 minutes.
      #                                                        ——《Pivotal Certified Professional Spring Developer Exam》
  server:
    wait-time-in-ms-when-sync-empty: 5

